version = 1
SPDX-PackageName = "circuits_i2c"
SPDX-PackageSupplier = "Frank Hunleth <fhunleth@troodon-software.com>"
SPDX-PackageDownloadLocation = "https://github.com/elixir-circuits/circuits_i2c"

[[annotations]]
path = ["README.md", "CHANGELOG.md", "PORTING.md", "RELEASE.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 Frank Hunleth"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [".gitignore", ".github/dependabot.yml", ".circleci/config.yml", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [".formatter.exs", "mix.lock", ".credo.exs", "mix.exs"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["c_src/linux/i2c-dev.h"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "GPL-2.0-or-later WITH Linux-syscall-note"

[[annotations]]
path = "assets/images/schematic-i2c.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 Erlang Solutions"
SPDX-License-Identifier = "SHL-0.51"
