version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 ".credo.exs",
 ".formatter.exs",
 ".github/dependabot.yml",
 ".gitignore",
 "CHANGELOG.md",
 "NOTICE",
 "PORTING.md",
 "RELEASE.md",
 "REUSE.toml",
 "mix.exs",
 "mix.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 Frank Hunleth"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["i2c_dev/c_src/linux/i2c-dev.h"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "GPL-2.0-or-later WITH Linux-syscall-note"

[[annotations]]
path = "assets/images/schematic-i2c.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 Erlang Solutions"
SPDX-License-Identifier = "SHL-0.51"
